FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git ca-certificates && update-ca-certificates
WORKDIR /src


COPY go.mod go.sum ./
RUN go mod download


COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o server ./cmd     # :contentReference[oaicite:0]{index=0}


FROM alpine:3.19

WORKDIR /app
RUN apk add --no-cache ca-certificates && update-ca-certificates

COPY --from=builder /src/server ./server
COPY configs ./configs           

EXPOSE 3000
CMD ["./server"]
