services:
  postgres:
    image: postgres:16-alpine
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: my_network

  api:
    build: .
    container_name: clean_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy   
    ports:
      - "3000:3000"
    networks: my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
  